/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciobd2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.TimerTask;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author damdu109
 */
public class Captcha extends javax.swing.JFrame {

    Random r = new Random();
    int numero1;
    String s1;
    String s2;
    String s3;
    String s4;

    private void startRandomNumberThread() {
        Timer timer = new Timer(5000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int randomNumber = r.nextInt(9990) + 10;
                numeroPanel.setText(String.valueOf(randomNumber));

            }
        });
        timer.start();
        
        numero.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                confirmarCaptcha();
            }
        });
        
        this.getRootPane().registerKeyboardAction(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonVolver.doClick(); 
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);;
        
        
    }
    
    private void confirmarCaptcha(){
    
    if (numero.getText().equals(String.valueOf(numeroPanel.getText()))) {

            try ( Connection conexion = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3307/biblioteca", "root", "");  PreparedStatement ps = conexion.prepareStatement("INSERT INTO usuarios (nombre, email, telefono, contraseña) VALUES (?, ?, ?, ?)")) {
                ps.setString(1, s1);
                ps.setString(2, s2);
                ps.setString(3, s3);
                ps.setString(4, s4);

                int filasInsertadas = ps.executeUpdate();
                if (filasInsertadas > 0) {

                    PreparedStatement ps2 = conexion.prepareStatement("SELECT * FROM usuarios WHERE id_usuario = (SELECT MAX(id_usuario) FROM usuarios);");
                    ResultSet rs = ps2.executeQuery();
                    while (rs.next()) {
                        numero1 = rs.getInt(1);

                    }

                    JOptionPane.showMessageDialog(this, "Usuario añadido correctamente.\n Tu ID de usuario es: " + numero1 + "\n Recuerdalo, lo necesitaras para iniciar sesion", "Añadido Correctamente", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha podido añadir al usuario.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    this.setVisible(false);
                }

            } catch (SQLException e) {
                System.out.println("Código de Error:" + e.getErrorCode() + "\n"
                        + "SLQState:" + e.getSQLState() + "\n"
                        + "Mensaje:" + e.getMessage() + "\n");
            }

        } else {

            JOptionPane.showMessageDialog(this, "Numero incorrecto. Intentelo de nuevo.", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    
    }

    public Captcha(int numero, String s1, String s2, String s3, String s4) {
        initComponents();
        startRandomNumberThread();
        numero1 = numero;
        this.s1 = s1;
        this.s2 = s2;
        this.s3 = s3;
        this.s4 = s4;
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        listo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        numeroPanel = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce el numero que aparecera a continuacion:");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Confirma que no eres un robot");

        numeroPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        botonVolver.setText("Soy un robot");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(110, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listo)
                    .addComponent(botonVolver))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        confirmarCaptcha();
    }//GEN-LAST:event_listoActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        
        JOptionPane.showMessageDialog(this, "Se ha cancelado la creacion de la cuenta.", "ERROR", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton listo;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numeroPanel;
    // End of variables declaration//GEN-END:variables
}
