/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciobd2;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author damdu109
 */
public class NewJFrame extends javax.swing.JFrame {

    int contador = 0;
    String administrador = "";
    int idUsuario = 0;
    String email = "";
    String telefono = "";
    String nombre = "";
    LocalDateTime fechaHoraActual = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String fechaFormateada = fechaHoraActual.format(formatter);

    public NewJFrame() {
        initComponents();
        this.setResizable(false);

        if (administrador.equals("")) {
            crearUsuario.setEnabled(true);
            inicioSesion.setEnabled(true);
            cerrarSesion.setEnabled(false);
            borrarUsuario.setEnabled(false);
            buscarUsuario.setEnabled(false);
            editarUsuario.setEnabled(false);
            realizarPrestamo.setEnabled(false);
            realizarDevolucion.setEnabled(false);
        }

        this.getRootPane().registerKeyboardAction(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonSalir.doClick();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);

    }
    

    public NewJFrame(String administrador, String id) throws HeadlessException {
        initComponents();

        this.setResizable(false);

        this.administrador = administrador;
        this.idUsuario = Integer.parseInt(id);

        if (administrador.equals("")) {
            crearUsuario.setEnabled(true);
            inicioSesion.setEnabled(true);
            cerrarSesion.setEnabled(false);
            borrarUsuario.setEnabled(false);
            buscarUsuario.setEnabled(false);
            editarUsuario.setEnabled(false);
            realizarPrestamo.setEnabled(false);
            realizarDevolucion.setEnabled(false);

        } else if (administrador.equals("S")) {
            crearUsuario.setEnabled(true);
            inicioSesion.setEnabled(false);
            cerrarSesion.setEnabled(true);
            borrarUsuario.setEnabled(true);
            buscarUsuario.setEnabled(true);
            editarUsuario.setEnabled(true);
            realizarPrestamo.setEnabled(true);
            realizarDevolucion.setEnabled(true);

        } else if (administrador.equals("N")) {
            crearUsuario.setEnabled(false);
            inicioSesion.setEnabled(false);
            cerrarSesion.setEnabled(true);
            borrarUsuario.setEnabled(false);
            buscarUsuario.setEnabled(false);
            editarUsuario.setEnabled(false);
            realizarPrestamo.setEnabled(true);
            realizarDevolucion.setEnabled(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearUsuario = new javax.swing.JButton();
        borrarUsuario = new javax.swing.JButton();
        editarUsuario = new javax.swing.JButton();
        buscarUsuario = new javax.swing.JButton();
        realizarPrestamo = new javax.swing.JButton();
        realizarDevolucion = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        inicioSesion = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        jLabel1.setText("MENU");
        jLabel1.setAlignmentY(0.0F);

        crearUsuario.setText("Crear Usuario");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });

        borrarUsuario.setText("Borrar Usuario");
        borrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUsuarioActionPerformed(evt);
            }
        });

        editarUsuario.setText("Modificar Usuario");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });

        buscarUsuario.setText("Buscar Usuario");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        realizarPrestamo.setText("Realizar un Prestamo");
        realizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPrestamoActionPerformed(evt);
            }
        });

        realizarDevolucion.setText("Realizar una Devolucion");
        realizarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarDevolucionActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.setAlignmentY(0.0F);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        inicioSesion.setText("Iniciar Sesion");
        inicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSesionActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(realizarPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(realizarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(botonSalir)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realizarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realizarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        CrearUsuario panta = new CrearUsuario();
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void borrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUsuarioActionPerformed
        BorrarUsuario panta = new BorrarUsuario();
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_borrarUsuarioActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        ModificarUsuario panta = new ModificarUsuario();
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas salir del programa?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_botonSalirActionPerformed

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        BuscarUsuario panta = new BuscarUsuario();
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_buscarUsuarioActionPerformed

    private void inicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSesionActionPerformed
        this.setVisible(false);
        IniciarSesion panta = new IniciarSesion();
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_inicioSesionActionPerformed

    private void realizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPrestamoActionPerformed
        RealizarPrestamo panta = new RealizarPrestamo(idUsuario);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null); // TODO add your handling code here:
    }//GEN-LAST:event_realizarPrestamoActionPerformed

    private void realizarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarDevolucionActionPerformed
        RealizarDevolucion panta = new RealizarDevolucion(idUsuario);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null); // TODO add your handling code here:
    }//GEN-LAST:event_realizarDevolucionActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas cerrar la sesion actual?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {

            administrador = "";
            this.setVisible(false);
            NewJFrame reset = new NewJFrame();
            reset.setVisible(true);
            reset.setLocationRelativeTo(null);

        }
    }//GEN-LAST:event_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarUsuario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton editarUsuario;
    private javax.swing.JButton inicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton realizarDevolucion;
    private javax.swing.JButton realizarPrestamo;
    // End of variables declaration//GEN-END:variables
}
